DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

CREATE TABLE users (

id INT AUTO_INCREMENT PRIMARY KEY,

name VARCHAR(100) NOT NULL,

email VARCHAR(255) NOT NULL UNIQUE,

password VARCHAR(255) NOT NULL,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

) ENGINE=InnoDB;

CREATE TABLE posts (

id INT AUTO_INCREMENT PRIMARY KEY,

title VARCHAR(255) NOT NULL,

body TEXT NOT NULL,

author_id INT NOT NULL,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


FOREIGN KEY (author_id) REFERENCES users(id)

ON DELETE CASCADE

) ENGINE=InnoDB;

CREATE TABLE comments (

id INT AUTO_INCREMENT PRIMARY KEY,

body TEXT NOT NULL,

post_id INT NOT NULL,

author_id INT NOT NULL,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


FOREIGN KEY (post_id) REFERENCES posts(id)

ON DELETE CASCADE,

FOREIGN KEY (author_id) REFERENCES users(id)

ON DELETE CASCADE

) ENGINE=InnoDB;
